FROM python:3-alpine

COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN python -m pip install -r requirements.txt
RUN apk add g++ zeromq-dev
RUN pip install numpy ipykernel
CMD ["sleep", "infinity"]
#ENTRYPOINT PYTHONUNBUFFERED=1 python mcts_agent.py
