FROM python:3.8-alpine

COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN python -m pip install -r requirements.txt
RUN apk add g++ zeromq-dev
RUN apk add build-base
RUN apt add llvm-dev
RUN pip install numpy ipykernel numba
CMD ["sleep", "infinity"]
# ENTRYPOINT PYTHONUNBUFFERED=1 python simple_agent.py
